### ISSUE TITLE
[Q:] If I want to only use your distance encoding code, which function should I use?

### ISSUE THREAD

**Issue by WangXuhongCN** [snap-stanford/distance-encoding#3]
If I want only to use your distance encoding code, which function should I start with?

**Comment by Abel0828** [comment]
Thanks for your question. I would suggest you start from the function `get_data_sample`
https://github.com/snap-stanford/distance-encoding/blob/f1a2681ef8d181dca30007415c9f946b9329fda2/utils.py#L247
It takes in an array of target node set indices, extracts their subgraphs, and calls different encoding functions based on the distance encoding flags that you set.
