### ISSUE TITLE
The basis of DEGNN

### ISSUE THREAD

**Issue by Junshuai-Song** [snap-stanford/distance-encoding#5]
The paper said "We choose GCN as the basic WLGNN and implement three variants of DEGNNs over it." in Section 5.
However, in the code, DEGNN uses TAGConv instead of GCNConv in the models.py file?

**Comment by lipan00123** [comment]
1-layer TAGConv is just GCN. Please correct me if I am wrong.

**Comment by lipan00123** [comment]
We use TAGConv to naturally make DE-GNN and DEA-GNN be in the same pipeline. And practitioners can use different K's to easily switch between DE-GNN and DEA-GNN.
