### ISSUE TITLE
Wrong debug info

### ISSUE THREAD

**Issue by LeVan146** [snap-stanford/distance-encoding#8]
I think it should be:
```python
    def get_best_acc(self, val):
        if val:
            max_step = int(np.argmax(np.array(self.val_accs)))
            return self.val_accs[max_step], max_step
        else:
            max_step = int(np.argmax(np.array(self.test_accs)))
            return self.test_accs[max_step], max_step

    def get_best_auc(self, val):
        if val:
            max_step = int(np.argmax(np.array(self.val_aucs)))
            return self.val_aucs[max_step], max_step
        else:
            max_step = int(np.argmax(np.array(self.test_aucs)))
            return self.test_aucs[max_step], max_step
```
rather than 
https://github.com/snap-stanford/distance-encoding/blob/45d49011a53bf1ad1679609b46689d458daa122b/train.py#L101-L113

**Comment by susheels** [comment]
No I think what they have done is correct because the intention is to get the test metric at the epoch step best validation was achieved. 

By doing what you suggest, we will just get the best val metric or best test metric which defeats the purpose of using validation data to select test metrics.

Hope this helps. I also hope the authors can comment on if what I said is right ?

**Comment by Abel0828** [comment]
> No I think what they have done is correct because the intention is to get the test metric at the epoch step best validation was achieved.
> 
> By doing what you suggest, we will just get the best val metric or best test metric which defeats the purpose of using validation data to select test metrics.
> 
> Hope this helps. I also hope the authors can comment on if what I said is right ?

Thank you, susheels! Your explanation is correct.

**Comment by LeVan146** [comment]
> No I think what they have done is correct because the intention is to get the test metric at the epoch step best validation was achieved.
> 
> By doing what you suggest, we will just get the best val metric or best test metric which defeats the purpose of using validation data to select test metrics.
> 
> Hope this helps. I also hope the authors can comment on if what I said is right ?

Thank you, I understand the idea of authors, I will close this issue ^^
